name: プルリクエストの自動作成
on:
  push:
    branches:
      - 'feature/*'
jobs:
  auto_create_pull_request:
    name: auto_create_pull_request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3-alpha
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: master
          labels: auto create
          title: ワークフローによって自動作成されたプルリクエスト
          body: テスト
          draft: true
